config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :games, only: [:create, :new, :show]
  resources :rounds, only: [:create, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players, dependent: :destroy
  has_many :rounds, dependent: :destroy

  validate :validate_players

  accepts_nested_attributes_for :players

    def validate_players
    errors.add(:players, "Please input 4 players") if players.size != 4
  end

end

app/models/other.rb
class Other < ApplicationRecord
  belongs_to :round
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game
  has_many :rounds
  validates :name, presence: true, length: { maximum: 15 }


end

app/models/round.rb
COL = [nil, "attaque", "defense"]

class Round < ApplicationRecord
  belongs_to :game
  belongs_to :player
  has_many :other
  validates :contract, presence: true, inclusion: { in: ["Prise", "Garde", "Garde Sans", "Garde Contre"] }
  validates :bouts, presence: true, inclusion: { in: [0, 1, 2, 3] }
  validates :petitAuBout, inclusion: { in: ["", "attaque", "defense"] }
  validates :chelem, inclusion: { in: ["", "anoncé", "non-anoncé", "non-réalisé"] }
  validates :levee, inclusion: { in: ["", "atc-S", "atc-D", "atc-T", "def-S", "def-D", "def-T"] }
  validate :sum_equals_91

  accepts_nested_attributes_for :other
  private

  def sum_equals_91
    p attackPts + defensePts != 91
    if attackPts + defensePts != 91
      errors.add(:base, "La somme des points d\'attaque et de défense doit etre 91")
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def create
    @new_game = Game.new(game_params)
    @new_game.start = Date.today
    set_players_score
    if @new_game.save
      redirect_to game_path(@new_game)
    else
      render "games/new"
    end
  end

  def new
    @game = Game.new
    4.times { @game.players.build }
  end

  def show
    @game = Game.find(params[:id])
  end
  private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:date, players_attributes: [:name])
  end

  def set_players_score
    @new_game.players.each {|player| player.score = 0}
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  def new
    @round = Round.new
    @round.game = Game.find(params[:game])
  end

  def create
    @round = Round.new(round_params)
    unless params[:round][:player_id].empty?
      @round.player = Player.find(params[:round][:player_id])
    end
    @round.game = Game.find(params[:round][:game_id])
    unless @round.help1.nil?
      @round.levee = @round.help1
    end
    @round.game.players.each { |player| update_player_score(player)}
    write_scores
    if @round.save
      redirect_to game_path(@round.game)
    else
      @round.game = Game.find(params[:round][:game_id])
      render "new"
    end
  end


  private

  def round_params
    params.require(:round).permit(:player, :game, :bouts, :defensePts, :contract, :attackPts, :petitAuBout, :levee, :chelem, :other)
  end

  def update_player_score(player)
    points = calculate_score
    player == @round.player ? player.score += points * 3 : player.score -= points
    player.save
  end

  def calculate_point_value(points)
    if @round.bouts == 0
      return points - 56
    elsif @round.bouts == 1
      return points - 51
    elsif @round.bouts == 2
      return points - 41
    else
      return points - 36
    end
  end


  def add_petit_au_bout(points)
    points += 10 if @round.petitAuBout == "attaque"
    points -= 10 if @round.petitAuBout == "defense"
    points
  end

  def contact_multplier(points)
    points *= 2 if @round.contract == "Garde"
    points *= 4 if @round.contract == "Garde Sans"
    points *= 6 if @round.contract == "Garde Contre"
    points
  end

  def add_levee(points)
    extra = 30 if @round.levee.include? "S"
    extra = 60 if @round.levee.include? "D"
    extra = 90 if @round.levee.include? "T"
    points += extra if @round.levee.include?("atc")
    points -= extra if @round.levee.include?("def")
    points
  end

  def add_chelem(points)
    points += 400 if @round.chelem == "anoncé"
    points += 200 if @round.chelem == "non-anoncé"
    points -= 200 if @round.chelem == "non-réalisé"
    points
  end

  def write_scores
    scores=""
    @round.game.players.each do |player|
      scores << "#{player.name}: #{player.score} |"
    end
    @round.scores = scores
  end


  def calculate_score
    points = calculate_point_value(@round.attackPts)
    points.positive? ? points += 25 : points -= 25
    points = add_petit_au_bout(points)
    points = contact_multplier(points)
    points = add_levee(points)
    points = add_chelem(points)
    points
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/new.html.erb
<div class="container-fluid lower-page newgame pt-3">
  <div class="row justify-content-center" >
    <div class="events-info col-10 col-lg-6">
      <%= form_with model: @game, local: true do |f| %>
       <p class="text-center">Indiquez le nom des 4 joueurs</p>
        <ul class="list">
          <% num = 1 %>
          <%= f.fields_for :players do |players_form| %>
            <li>
              <%= players_form.label "Joueur #{num}" %>
              <%= players_form.text_field :name, required: true%>
            </li>
            <% num += 1 %>
          <% end %>
        <%= f.submit "Commencer la partie",  class: "button-start", value: "Commencer la partie", id: "submit" %>
        </ul>
      <% end %>
     </div>
  </div>
</div>

app/views/games/show.html.erb
<div class="pt-3">
  <% @game.rounds.sort.each_with_index do |round, index| %>
    <p class="mb-0"> <%= "Manche #{index + 1}:" %></p>
    <%=  round.scores %>
    <br>
  <% end %>

  <%= link_to new_round_path(game: @game), class: "btn-round sticky removelinkdefault" do %>
    <i class="fas fa-plus"></i>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <%= render "shared/topbar" %>
    <div class="pages">
      <div class="container">
        <body>
          <%= yield %>
          <%= javascript_include_tag 'application' %>
          <%= javascript_pack_tag 'application' %>
        </body>
      </div>
    </div>
</html>

app/views/pages/home.html.erb
<br>
<%= link_to  new_game_path, class: "mx-auto removelinkdefault" do %>
  <%= render "shared/button"  %>
<% end %>
<br>
  <h5>Charger une ancienne partie:</h5>

  <% Game.all.each do |game|%>
    <%= render "shared/game-card", game: game%>
  <% end %>

app/views/rounds/new.html.erb
<div class = "marker"></div>
<div class="container-fluid lower-page new-game pt-10">
  <div class="row justify-content-center" >
    <div class="events-info col-10 col-lg-6">
      <%= simple_form_for @round do |f| %>
        <%= f.error_notification %>
        <%= f.association :player, label: false, collection: @round.game.players, prompt: "Preneur" %>
        <%= f.input :game_id,  :as => :hidden, default: params[:game] %>
        <%= f.input :contract, label: false, collection: ["Prise", "Garde", "Garde Sans", "Garde Contre"], prompt: "Contrat" %>
       <%#= render "shared/bouts" %>
        <%= f.input :bouts, label: "Bouts", collection: [0, 1, 2, 3] %>
        <div class="d-flex justify-content-between">
          <%= f.input :attackPts, label: "Attaque", input_html: {value: 91, class: "attackPts"} %>
          <%= f.input :defensePts,label: "Défense", input_html: {value: 0, class: "defensePts"} %>
        </div>
        <div class="d-flex justify-content-between">
          <%= f.input :help, as: :boolean, label: 'Petit au Bout',input_html: {class: "click-pab"}  %>
          <%= f.input :help, as: :boolean, label: 'Levée',input_html: {class: "click-levee"}  %>
          <%= f.input :help, as: :boolean, label: 'Chelem',input_html: {class: "click-chelem"}  %>
        </div>
        <div class="d-flex justify-content-between">
          <div class="d-none pab-choix">
            <%= f.input :petitAuBout, label: '', as: :radio_buttons, collection: ['attaque','defense']%>
          </div>
          <div>
            <div class="d-none levee-choix">
              <div class="attaque">
                <%= f.input :help, as: :boolean, label: 'attaque',input_html: {class: "click-levee"}  %>
              </div>
              <div class="defense">
                <%= f.input :help, as: :boolean, label: 'defense',input_html: {class: "click-levee "}  %>
              </div>
            </div>
            <div class="choices">
              <div class="d-none atc-choix">
                <%= f.input :levee, label: '', as: :radio_buttons, collection: [["Simple", "atc-S" ], ["Double", "atc-D" ], ["Triple", "atc-T" ]] %>
              </div>
              <div class="d-none d-choix">
                <%= f.input :help1, label: '', as: :radio_buttons, collection: [["Simple", "def-S" ], ["Double", "def-D" ], ["Triple", "def-T" ]] %>
              </div>
            </div>
          </div>
          <div class="d-none chelem-choix">
            <%= f.input :chelem, label: '', as: :radio_buttons, collection: ["anoncé", "non-anoncé", "non-réalisé"] %>
          </div>
        </div>

        <div class="text-center">
          <%= f.button :submit, 'Créer la manche', class: "button-start new-round" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_bouts.html.erb
<div class="d-flex justify-content-between">
  <h4>Bouts:</h4>
  <% bouts = [] %>
  <div class="btn-group-toggle petit" data-toggle="buttons">
    <label class="btn btn-success active">
      <input type="checkbox" checked autocomplete="off"> Petit
    </label>
  </div>
  <button type="button" class="btn btn-success" data-toggle="button" aria-pressed="false" autocomplete="off">
   <%= "  Petit  " %>
  </button>
<button type="button vingthEtUn" class="btn btn-success" data-toggle="button" aria-pressed="false" autocomplete="off">
  <%= "    21    " %>
</button>
<button type="button excuse" class="btn btn-success" data-toggle="button" aria-pressed="false" autocomplete="off">
 <%= "  Excuse  " %>
</button>
</div>

app/views/shared/_button.html.erb
<div class="button1 mx-auto">
  <i class="fas fa-plus-circle"></i>
  <h1>Nouvelle partie</h1>
</div>

app/views/shared/_game-card.html.erb
<div class="card removelinkdefault">
  <div class="d-flex  mt-3">
    <div class="d-flex date ">
      <i class="far fa-calendar-alt mr-1"></i>
    <%= game.start.strftime("%d/%m") %>
    </div>
    <div class="d-flex users">
      <i class="fas fa-users mr-1"></i>
      <% game.players.each do |player|%>
        <%= player.name %>
      <% end %>
    </div>
  </div>
<%= link_to "", game_path(game), class: "link" %>
</div>

app/views/shared/_topbar.html.erb
<div class="topbar">
  <div class="d-flex justify-content-around align-items-center">
    <%= link_to root_path, class: "removelinkdefault" do%>
      <i class="fas fa-home"></i>
    <% end %>
    <p class="mt-3">Tarot: compteur de points</p>
  </div>
</div>